# -*- coding: utf-8 -*-
"""MerMYEU.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OWUVEEXMJf10QBEiUOp4mn9KHMowpPPD
"""

import streamlit as st
import pandas as pd
import os

# --- CẤU HÌNH GIAO DIỆN ---
st.set_page_config(page_title="MYÊU MERCHANDISE", layout="centered")

st.markdown("""
<style>
    /* Chống rớt chữ và nổi khối 3D cho Title */
    .main-title {
        color: #800020; /* Đỏ bọc đô */
        text-shadow: 2px 2px 0px #e6d3d3, 4px 4px 5px rgba(0,0,0,0.4);
        text-align: center;
        font-weight: 900;
        font-size: 2.5rem;
        line-height: 1.2;
        margin-bottom: 25px;
    }

    /* Ép hiển thị 2 dòng tĩnh, không rớt chữ lộn xộn trên mobile */
    .main-title span {
        display: block;
        white-space: nowrap;
    }

    /* Màu hồng đậm sang tím cho các thông tin quan trọng */
    .highlight-text {
        color: #C71585; /* MediumVioletRed */
        font-weight: bold;
        font-size: 1.1rem;
    }

    h3, h4 {
        color: #8B008B; /* DarkMagenta */
    }

    @media screen and (max-width: 768px) {
        .main-title {
            font-size: 1.6rem; /* Thu nhỏ gọn lại để fit màn mobile */
        }
    }
    /* Đổi màu Gradient Hồng Đậm sang Tím cho tất cả Nút bấm */
    div.stButton > button {
        background: linear-gradient(90deg, #C71585, #8B008B) !important;
        color: white !important;
        border: none !important;
        font-weight: bold !important;
        border-radius: 8px !important;
        transition: 0.3s;
    }
    
    /* Hiệu ứng khi lướt chuột qua nút */
    div.stButton > button:hover {
        background: linear-gradient(90deg, #8B008B, #C71585) !important;
        box-shadow: 0px 4px 10px rgba(139, 0, 139, 0.4) !important;
    }

    /* Style Gradient cho dòng Thống kê */
    .section-title {
        background: linear-gradient(90deg, #C71585, #8B008B);
        -webkit-background-clip: text;
        -webkit-text-fill-color: transparent;
        font-weight: 900;
        font-size: 1.6rem;
        margin-top: 20px;
        margin-bottom: 15px;
    }
</style>
""", unsafe_allow_html=True)

# Hiển thị Title
st.markdown('<div class="main-title"><span>MYÊU MERCHANDISE</span><span>PICK AT EVENT</span></div>', unsafe_allow_html=True)

# --- THIẾT LẬP DỮ LIỆU ---
GSHEET_URL = "https://docs.google.com/spreadsheets/d/1tHLQoD_HkU9l_aqXnidH840y_KjO-T9F_3lGpRfQqW4/export?format=csv&gid=724869545"
DELIVERED_FILE = "delivered_log.csv"

@st.cache_data(ttl=5) # Load lại data gốc mỗi 5s
def load_main_data():
    try:
        # THÊM dtype=str Ở ĐÂY để giữ nguyên số 0 ở đầu
        df = pd.read_csv(GSHEET_URL, dtype=str)
        
        if '4 Số đuôi' in df.columns:
            df['4 Số đuôi'] = df['4 Số đuôi'].str.replace('.0', '', regex=False).str.zfill(4)
        if 'ĐT' in df.columns:
            df['ĐT'] = df['ĐT'].str.replace('.0', '', regex=False)
        return df
    except Exception as e:
        st.error("Chưa kết nối được Google Sheet. Vui lòng kiểm tra lại link.")
        return pd.DataFrame()

def load_delivered_data():
    if os.path.exists(DELIVERED_FILE):
        return pd.read_csv(DELIVERED_FILE)
    return pd.DataFrame(columns=["ĐT", "Loại Merchandise"])

def mark_as_delivered(phone, merch_type):
    # Ghi log lịch sử giao hàng
    new_record = pd.DataFrame([{"ĐT": str(phone), "Loại Merchandise": merch_type}])
    if os.path.exists(DELIVERED_FILE):
        new_record.to_csv(DELIVERED_FILE, mode='a', header=False, index=False)
    else:
        new_record.to_csv(DELIVERED_FILE, index=False)

df_main = load_main_data()
df_delivered = load_delivered_data()

# --- TÍNH NĂNG TÌM KIẾM ---
st.markdown('**Số điện thoại của người nhận:**')
st.markdown('*Chỉ cần gõ 4 số đuôi điện thoại, trong trường hợp có người trùng 4 số đuôi, hệ thống sẽ hiện yêu cầu nhập full số điện thoại*')

search_input = st.text_input("Nhập số điện thoại vào đây (ẩn label gốc)", label_visibility="collapsed")

if st.button("Tìm giúp MYêu", type="primary"):
    if search_input:
        # Phân luồng tìm kiếm: Gõ <= 4 ký tự thì tìm theo đuôi, gõ dài hơn thì tìm full
        if len(search_input) <= 4:
            matched_df = df_main[df_main['4 Số đuôi'].str.contains(search_input, na=False)]
        else:
            matched_df = df_main[df_main['ĐT'].str.contains(search_input, na=False)]

        if matched_df.empty:
            st.warning("Không tìm thấy thông tin phù hợp!")
        else:
            # Check rủi ro trùng 4 số đuôi
            unique_phones = matched_df['ĐT'].unique()
            if len(unique_phones) > 1:
                st.error("⚠️ Nhập full số điện thoại nha (Có nhiều người trùng 4 số đuôi này)")
            else:
                # Tìm thấy duy nhất 1 người
                user_name = matched_df.iloc[0].get('Tên', 'Không rõ')
                st.markdown(f"**Thông tin người nhận:** <span class='highlight-text'>{user_name}</span>", unsafe_allow_html=True)
                st.markdown("---")

                # Hiển thị từng món hàng người đó đặt
                for index, row in matched_df.iterrows():
                    phone_val = str(row['ĐT'])
                    merch_val = str(row.get('Loại Merchandise', ''))
                    qty_val = row.get('SL', 0)
                    size_val = row.get('Size áo', '')

                    # Logic kiểm tra món này đã được nhấn giao chưa
                    is_delivered = False
                    if not df_delivered.empty:
                        # Nếu trong file log đã có ghi nhận SĐT này nhận món này
                        check = df_delivered[(df_delivered['ĐT'] == phone_val) & (df_delivered['Loại Merchandise'] == merch_val)]
                        if not check.empty:
                            is_delivered = True

                    with st.container(border=True):
                        st.markdown(f"**Merchandise:** <span class='highlight-text'>{merch_val}</span>", unsafe_allow_html=True)
                        st.markdown(f"**Số lượng:** <span class='highlight-text'>{qty_val}</span>", unsafe_allow_html=True)

                        if pd.notna(size_val) and str(size_val).strip() != '':
                            st.markdown(f"**Size áo:** <span class='highlight-text'>{size_val}</span>", unsafe_allow_html=True)

                        # Xử lý nút bấm
                        if is_delivered:
                            st.button("✅ Đã nhận hàng", key=f"done_{index}", disabled=True)
                        else:
                            if st.button("Đã giao hàng", key=f"deliver_{index}", type="primary"):
                                mark_as_delivered(phone_val, merch_val)
                                st.rerun()

# --- THỐNG KÊ (DASHBOARD REAL-TIME) ---
st.markdown("---")
st.markdown('<div class="section-title">📊 THỐNG KÊ KHO MERCHANDISE</div>', unsafe_allow_html=True)

if not df_main.empty:
    # Gom nhóm tính tổng số lượng phải giao theo từng loại
    # Ép kiểu SL về numeric để cộng tổng chính xác
    df_main['SL'] = pd.to_numeric(df_main['SL'], errors='coerce').fillna(0)
    summary_df = df_main.groupby('Loại Merchandise')['SL'].sum().reset_index()
    summary_df.rename(columns={'SL': 'Tổng SL'}, inplace=True)

    # Gom nhóm tính số lượng đã thực giao
    if not df_delivered.empty:
        # Gom các record đã giao theo Merchandise
        delivered_counts = df_delivered.groupby('Loại Merchandise').size().reset_index(name='Đã nhận')
        summary_df = pd.merge(summary_df, delivered_counts, on='Loại Merchandise', how='left')
    else:
        summary_df['Đã nhận'] = 0

    summary_df['Đã nhận'] = summary_df['Đã nhận'].fillna(0).astype(int)
    summary_df['Còn lại'] = summary_df['Tổng SL'] - summary_df['Đã nhận']

    st.dataframe(summary_df, use_container_width=True, hide_index=True)

st.markdown("---")
with st.expander("🛠️ Admin: Reset Dữ liệu Test"):
    st.warning("Nút này sẽ xóa toàn bộ lịch sử 'Đã giao hàng'. Chỉ dùng khi test!")
    if st.button("Xóa trắng dữ liệu"):
        if os.path.exists(DELIVERED_FILE):
            os.remove(DELIVERED_FILE)
            st.success("Đã reset thành công!")
            st.rerun()
